### ISSUE TITLE
Provide source code for the Online Example

### ISSUE THREAD

**Issue by Rohan-Rajesh** [altmshfkgudtjr/react-epub-viewer#11]
**Is your feature request related to a problem? Please describe.**
When I first saw this library, I looked through the online  example and really liked how it looked, I looked through the GitHub but I couldn't find the source code for the example

**Describe the solution you'd like**
If you could add the example code to the repository it would be appreciated

**Comment by altmshfkgudtjr** [comment]
Hi @Rohan-Rajesh, 

You can check the code this [demo branch](https://github.com/altmshfkgudtjr/react-epub-viewer/tree/demo)

**Comment by Rohan-Rajesh** [comment]
Oh, sorry for noticing that, thanks a lot
