### ISSUE TITLE
How to add extra fonts and bookmarks?

### ISSUE THREAD

**Issue by technophilix** [altmshfkgudtjr/react-epub-viewer#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by altmshfkgudtjr** [comment]
Hi! [technophilix](https://github.com/technophilix)

You should be able to find what you're looking for in the following [demo branch](https://github.com/altmshfkgudtjr/react-epub-viewer/tree/demo).

If you can't find it on that branch, please let me know.
