### ISSUE TITLE
Changing pages?

### ISSUE THREAD

**Issue by bobkataboo** [altmshfkgudtjr/react-epub-viewer#15]
Hello,

I am trying to change the page without keyboard arrows. In my case I'm trying to use the reader on a mobile phone and I can't access keyboard arrows there. I can do it with left/right swipe gestures but I cannot figure out how to change the page.

So the question is:
How do I programmatically change the page to the next/previous one?

**Comment by altmshfkgudtjr** [comment]
As you can see if you check the [module](https://github.com/altmshfkgudtjr/react-epub-viewer/blob/main/src/modules/epubViewer/EpubViewer.tsx), the page transition of the Epub file is done as follows.

https://github.com/altmshfkgudtjr/react-epub-viewer/blob/8d7af938db078ca2223870481541cf71a1a2b375/src/modules/epubViewer/EpubViewer.tsx#L58-L67

And I added an event to that viewer.

https://github.com/altmshfkgudtjr/react-epub-viewer/blob/8d7af938db078ca2223870481541cf71a1a2b375/src/modules/epubViewer/EpubViewer.tsx#L137-L161

Have any questions been answered?
