### ISSUE TITLE
epub-viewer doesn't display on the browser  

### ISSUE THREAD

**Issue by codeporan** [altmshfkgudtjr/react-epub-viewer#28]
Hi there,

I can not see epub-viewer in the chrome browser due to block origin

![Screenshot from 2022-03-10 15-34-35](https://user-images.githubusercontent.com/38273152/157633346-37f59e64-fe36-42c8-8e12-1694bf56971e.png)
![Screenshot from 2022-03-10 15-34-35](https://user-images.githubusercontent.com/38273152/157633369-964bf5b1-c00f-4a36-8f38-02ce54ada51a.png)

**Comment by altmshfkgudtjr** [comment]
What happened?

I don't think there is any reason to get this error! `blocked a frame with origin`

The epub viewer iframe doesn't show other domains, it just creates a new html.

I want to know if this error occurs only in the Chrome browser.


**[This is my chrome browser]**
![image](https://user-images.githubusercontent.com/47492535/157778004-5b16edbf-c670-4a20-83d6-5ac42423e92d.png)

**Comment by codeporan** [comment]
![Screenshot from 2022-03-15 18-04-13](https://user-images.githubusercontent.com/38273152/158374028-7f56f177-bdc2-4b2d-ba21-b7054d47449f.png)

This is my Linux chrome dev tool. It doesn't work linux and also mac  However, It works in incognito mode

**Comment by codeporan** [comment]
![Screen Shot 2022-03-15 at 6 08 50 PM](https://user-images.githubusercontent.com/38273152/158374929-8e084ff2-77cf-4c27-b8f7-0f8806872fd6.png)

this is only for mac book in chrome . it doesn't work also , but works only for incognito

**Comment by altmshfkgudtjr** [comment]
@hero9991 
The photo is the official demo site. 
The demo code doesn't have multiple iframes and I haven't been able to reproduce the situation where this happens.

**Comment by hero9991** [comment]
@altmshfkgudtjr 
Oh, I didn't notice it was the original demo. From my side I can confirm that the demo works without cross-domain errors.
Maybe it's thrown due to some specific browser settings but I can not even guess which ones.
