### ISSUE TITLE
EpubViewer doesn't re-render when 'epubOptions' & 'style' prop changes

### ISSUE THREAD

**Issue by WEEFAA** [altmshfkgudtjr/react-epub-viewer#3]
**Describe the bug**
When passing a different value to _epubOptions_ & _style_ props, EpubViewer doesn't re-evaluate and render with the new props

**To Reproduce**
1. Render simple viewer using the EpubViewer
2. Pass the required props and both (epubOptions & style) props
3. Make a toggle to change the value of epubOptions & style prop

**Expected behavior**
EpubViewer should re-render and display changes with the new passed in props

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Single Language 64-bit
 - Browser: Firefox
 - Version: 88.0.1

**Additional context**
```javascript 
        useEffect(() => {
             // some effect to change the value of props 
             setTimeout(() => {
                setBookOption({...})
                setBookStyle({...})
             },500)
          
             // should re-render the viewer after the delay
        },[]) 

	<EpubViewer
		ref={viewerRef}
		url={url}
		epubFileOptions={epubFileOptions}
		epubOptions={bookOption} // doesn't re-render
		style={bookStyle} // doesn't re-render
		rendtionChanged={renditionChange}
		loadingView={loadingView || <LoadingView />}
		bookChanged={onBookInfoChange}
		pageChanged={onPageChange}
		tocChanged={onTocChange}
		selectionChanged={onContextMenu}
	/>

```

**Comment by altmshfkgudtjr** [comment]
Hi!

I confirmed the issue.

First of all, I am sorry for the bug. 

And I will check and fix the problem as soon as possible.

Thank you!  😀

**Comment by WEEFAA** [comment]
Yes,

Thank you so much for your quick response. Giving you that HIGH FIVE on the form of a star. 

Will wait for the fix!
Thanks again, 🐳! Excellent project nonetheless.

**Comment by altmshfkgudtjr** [comment]
corrected this issue!

Thank you for trusting and waiting!
