### ISSUE TITLE
Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

### ISSUE THREAD

**Issue by stevcooo** [altmshfkgudtjr/react-epub-viewer#36]
Hi,
I'm trying to implement this demo code in my app but when I try it on Chrome I get this error
`Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

This is my code:
```
import { useState, useRef } from 'react';
import { EpubViewer, ReactEpubViewer } from 'react-epub-viewer';

export default function ReadComponent({ book, navigation }) {
    const viewerRef = useRef(null);
    const [pageLocation, setPageLocation] = useState('');
    const onPageChangeHandler = (page) => {
        setPageLocation(`${page.currentPage.toString()}/${page.totalPage}`);
    };
    return (
        <div style={{ position: 'relative', height: '100%' }}>
            <div>{pageLocation}</div>
            <ReactEpubViewer
                url={require(`../assets/files/${book.fileName}`)}
                ref={viewerRef}
                onPageChange={onPageChangeHandler}
            />
        </div>
    );
}

```
![image](https://user-images.githubusercontent.com/533009/162981207-a6c4d85e-1179-4c7c-ad87-7d276c12fa6c.png)
Do you have any idea how can I resolve this one?

**Comment by altmshfkgudtjr** [comment]
It seems to duplicate with the following #28 issue.

We are currently working on the cause of the problem.

**Comment by altmshfkgudtjr** [comment]
https://github.com/futurepress/epub.js/

**Comment by altmshfkgudtjr** [comment]
https://github.com/futurepress/epub.js/

I found the problem late. 
Which Epub File did you use? 
My guess is that the script exists in that Epub file.
