### ISSUE TITLE
How can I create different themes styles ?

### ISSUE THREAD

**Issue by mistralaix** [altmshfkgudtjr/react-epub-viewer#37]
Hi,
I would like to have that kind of options in my react app while using this library:
![Capture d’écran 2022-04-16 à 10 36 24](https://user-images.githubusercontent.com/25264889/163668366-9bd368bd-f31c-452a-8486-746aecf37cf3.png)

I've seen that I can use the bookStyleOptions but there's no option in order to set a custom font color or a custom background color.
I've tried to use the props `viewerStyleURL` and I managed to modify the background color but no success with the font color.

I've found this example on the epubjs repo: https://github.com/futurepress/epub.js/blob/master/examples/themes.html
However, in order to register multiple themes, I would need to have access to the rendition property through the ViewerRef object.
Can you let us access this property?

Or do you have another solution?

Thank you a lot for this lib btw, really good job!

**Comment by altmshfkgudtjr** [comment]
Hmm

If you are using ReactViewer there is no way to access the Rendition property.

However, in that case, if you use EpubViewer, you can access Rendition.

Thank you!
