### ISSUE TITLE
Stop user from copying text

### ISSUE THREAD

**Issue by Pustaka-Digital-Media** [altmshfkgudtjr/react-epub-viewer#38]
**Describe the bug**
For our website, we noticed that users are able to copy the text for the entire epub file and distribute it, is there any way to stop this from happening?

**To Reproduce**
1. Open demo project
2. Copying text works

**Expected behavior**
The user should not be able to copy text from the epub file

**Additional context**
I already tried adding the `user-select: none` css tag, but it doesn't seem to affect the `iframe`, I'm using the `ReactEpubViewer` component

**Comment by altmshfkgudtjr** [comment]
I think the functionality you asked for can be resolved through the CSS URL below.

https://github.com/altmshfkgudtjr/react-epub-viewer/blob/a0f2719b7c967d3f43f31ee2956c303a6cceb6f5/src/modules/reactViewer/ReactViewer.tsx#L297-L299

Would you like to check it out?

**Comment by Pustaka-Digital-Media** [comment]
Could you please show me an example with an entire component?

**Comment by altmshfkgudtjr** [comment]
Sorry my answer was late.

Examples include:
https://codesandbox.io/s/react-playground-forked-ju3039?file=/index.js
