### ISSUE TITLE
Documentation: EpubViewer 'style' props documentation 

### ISSUE THREAD

**Issue by WEEFAA** [altmshfkgudtjr/react-epub-viewer#5]
Is there any reference or example of how the _style_ prop properties should look like? 

I am trying to customize the look of my epub viewer such as Font Size, Font Family, Line Height, Horizontal Margin, and Vertical Margin. Basically, I'm trying to implement the same settings as the one I've seen in the [demo](https://altmshfkgudtjr.github.io/react-epub-viewer/)

Thanks!

**Comment by altmshfkgudtjr** [comment]
If you want the same settings as the demo page, it would be nice to refer to the following [this code file](https://github.com/altmshfkgudtjr/react-epub-viewer/blob/demo/src/containers/Reader.tsx).

You can check the code of the actual demo page!

I hope you get the answer in that code. :)

**Comment by altmshfkgudtjr** [comment]
Thank you for actively using my library! 👍

**Comment by WEEFAA** [comment]
Cool!

Yes, I've tried it with this implementation (with EpubViewer component not the ReactEpubViewer). Unfortunately, only the height & width property works with the ```style``` prop. Other css properties doesn't work e.g. fontSize, fontFamily. 

Do you have any clue why it wouldn't work?

**Comment by altmshfkgudtjr** [comment]
In my opinion, the reasons why font-related styles are not applied are as follows.

The style passed to the `style` prop is applied outside the `Viewer Iframe` `div` wrapper.

![image](https://user-images.githubusercontent.com/47492535/119430422-b9109280-bd4b-11eb-8bbc-9981baa484d9.png)

The iframe cannot inherit the style of the external DOM.

So, to apply the style to the `Viewer Iframe` itself, you need to control `rendition`.

Below is an example code.

```javascript
// setting rendition state

const [rendition, setRendition] = useState<Rendition | null>(null);

const rendtionChanged = (rendition: Rendition) => setRendition(rendition);

return (
  <EpubViewer
    rendtionChanged={rendtionChanged}
    ...
  />
);
```

```javascript
// apply style to the viewer iframe.

const style = {
  "font-family": "Roboto",
  "font-size": "14px !important"
};

rendition.themes.register("default", style);
```

**Comment by WEEFAA** [comment]
That seems to be the right solution and feasible in my case. 

Just a question, do I need to update the book again to recalculate the pages? I'm currently doing it this way and it seems that triggering the themes this way doesn't update the book

```javascript
rendition.themes.default({
        p: {
		'font-size': `${fontSize}px !important`,
		'font-family': `${FONT[fontFamily]} !important`,
	},
})
```

Thanks for your quick response! So cool!

**Comment by WEEFAA** [comment]
The solutions works pretty well on my end. Except the book has to be re-updated with ```rendition.currentLocation()``` after the theme update 

I just want to mention this issue for future reference.
https://github.com/futurepress/epub.js/issues/982

You can close this issue, thanks NB!

**Comment by altmshfkgudtjr** [comment]
Thank you for updating the resolution link for the issue.
