### ISSUE TITLE
is it support with React Native?

### ISSUE THREAD

**Issue by lyseiha** [altmshfkgudtjr/react-epub-viewer#6]

**Comment by altmshfkgudtjr** [comment]
I'm sorry,

`react-epub-viewer` library is not supoorted React-Natvie. 😥

**Comment by lyseiha** [comment]
Do you plan to do one? :(

**Comment by altmshfkgudtjr** [comment]
There are other projects currently in progress, so it will be difficult in the near future.

However, if anyone interested in the Epub Viewer is making a PR, there is a willingness to review it!

Thank you! 

:)
