### ISSUE TITLE
How to store current page on localstorage

### ISSUE THREAD

**Issue by paras205** [altmshfkgudtjr/react-epub-viewer#8]
How to store current page on localstorage

**Comment by altmshfkgudtjr** [comment]
if you using `ReactViewer`, using `onPageChange` method.
If you using `EpubViewer`, using `pageChanged` method.

Just pass it as props.

**Comment by paras205** [comment]
@altmshfkgudtjr if I close the reader and open it again it gives me page one rather than the last location and saving the location on localstorage does not help either

**Comment by altmshfkgudtjr** [comment]
https://github.com/altmshfkgudtjr/react-epub-viewer/blob/0eca3d003f8a830ecffb513dd7d38b630687a91d/src/containers/Reader.tsx#L78-L85

How about executing the following code through useEffect ?

```javascript
useEffect(() => {
  if(!viewerRef.current) return;
  
  const targetCFI = window.localStorage.getItem('savedCFI')
  viewerRef.current.setLocation(loc);
}, [viewerRef]);
```

**Comment by altmshfkgudtjr** [comment]
or using rendition

```javascript
const App = () => {
  const ref = useRef(null);
  const [rendition, setRendition] = useState(null);

  const onRenditionChanged = (rendition) => setRendition(rendition);

  useEffect(() => {
    if (!rendition) return;
    const targetCFI = window.localStorage.getItem("savedCFI");
    rendition.display(targetCFI);
  }, [rendition]);

  return (
    <div style={{ position: "relative", height: "100vh" }}>
      <EpubViewer
        ref={ref}
        url="https://altmshfkgudtjr.github.io/react-epub-viewer/files/Alices%20Adventures%20in%20Wonderland.epub"
        rendtionChanged={onRenditionChanged}
      />
    </div>
  );
};
```

**Comment by paras205** [comment]
@altmshfkgudtjr
 where do you set this  window.localStorage.getItem("savedCFI");

**Comment by altmshfkgudtjr** [comment]
```javascript
const onPageChange = (pageInfo) => {
    setChapterName(pageInfo.chapterName);
    setPage(pageInfo.currentPage);
    setTotalPage(pageInfo.totalPage);

    // like this?
    window.localStorage.setItem('savedCFI', pageInfo.startCfi);
};

return (
  <div style={{ position: "relative", height: "100%" }}>
      <ReactEpubViewer
        ref={ref}
        url="https://altmshfkgudtjr.github.io/react-epub-viewer/files/Alices%20Adventures%20in%20Wonderland.epub"
        onPageChange={onPageChange}
      />
    </div>
  );
);
```

**Comment by paras205** [comment]
Yes,exactly thats my question if Page is reloaded onpagechange tiggered and the current cfi or saveCfi is page 0 not last located page.

**Comment by altmshfkgudtjr** [comment]
oh,

Has confirmed. I'll check it out.

**Comment by paras205** [comment]
and one more thing, Is it possible to add reading time and percentage? If possible,how?

**Comment by altmshfkgudtjr** [comment]
> Yes,exactly thats my question if Page is reloaded onpagechange tiggered and the current cfi or saveCfi is page 0 not last located page. Try reloading browser

As a result of testing in [sandbox](https://codesandbox.io/s/react-playground-forked-c483n?file=/index.js), it was confirmed that it works well.

Can you check it out?

```javascript
const App = () => {
  const ref = useRef(null);
  const [rendition, setRendition] = useState(null);
  const [chapterName, setChapterName] = useState("");
  const [page, setPage] = useState(0);
  const [totalPage, setTotalPage] = useState(0);

  const onRenditionChanged = (rendition) => setRendition(rendition);

  const onPageChange = (pageInfo) => {
    setChapterName(pageInfo.chapterName);
    setPage(pageInfo.currentPage);
    setTotalPage(pageInfo.totalPage);
    window.localStorage.setItem("savedCFI", pageInfo.startCfi);
  };

  useEffect(() => {
    if (!rendition) return;
    const targetCFI = window.localStorage.getItem("savedCFI");
    rendition.display(targetCFI);
  }, [rendition]);

  return (
    <div style={{ position: "relative", height: "100vh" }}>
      <h2>
        Page: {page} / {totalPage} [{chapterName}]
      </h2>
      <EpubViewer
        ref={ref}
        url="https://altmshfkgudtjr.github.io/react-epub-viewer/files/Alices%20Adventures%20in%20Wonderland.epub"
        pageChanged={onPageChange}
        rendtionChanged={onRenditionChanged}
      />
    </div>
  );
};
```

**Comment by altmshfkgudtjr** [comment]
> and one more thing, Is it possible to add reading time and percentage? If possible,how?

`percentage` is simply the `current number of pages` divided by the `total number of pages`.

but what is `reading time`?

**Comment by paras205** [comment]
total time user spend reading a book

**Comment by paras205** [comment]
> > Yes,exactly thats my question if Page is reloaded onpagechange tiggered and the current cfi or saveCfi is page 0 not last located page. Try reloading browser
> 
> As a result of testing in [sandbox](https://codesandbox.io/s/react-playground-forked-c483n?file=/index.js), it was confirmed that it works well.
> 
> Can you check it out?
> 
> ```js
> const App = () => {
>   const ref = useRef(null);
>   const [rendition, setRendition] = useState(null);
>   const [chapterName, setChapterName] = useState("");
>   const [page, setPage] = useState(0);
>   const [totalPage, setTotalPage] = useState(0);
> 
>   const onRenditionChanged = (rendition) => setRendition(rendition);
> 
>   const onPageChange = (pageInfo) => {
>     setChapterName(pageInfo.chapterName);
>     setPage(pageInfo.currentPage);
>     setTotalPage(pageInfo.totalPage);
>     window.localStorage.setItem("savedCFI", pageInfo.startCfi);
>   };
> 
>   useEffect(() => {
>     if (!rendition) return;
>     const targetCFI = window.localStorage.getItem("savedCFI");
>     rendition.display(targetCFI);
>   }, [rendition]);
> 
>   return (
>     <div style={{ position: "relative", height: "100vh" }}>
>       <h2>
>         Page: {page} / {totalPage} [{chapterName}]
>       </h2>
>       <EpubViewer
>         ref={ref}
>         url="https://altmshfkgudtjr.github.io/react-epub-viewer/files/Alices%20Adventures%20in%20Wonderland.epub"
>         pageChanged={onPageChange}
>         rendtionChanged={onRenditionChanged}
>       />
>     </div>
>   );
> };
> ```

This works.Thanks a lot

**Comment by Rohan-Rajesh** [comment]
Could you please provide an example with `ReactEpubReader` everything works fine except setting the epub CFI on page load, using the `useEffect` provided above results in an error saying: `viewerRef.current.setLocation is not a function`, any help would be appreciated.

Thanks

**Comment by technophilix** [comment]
set it in location.
first do it
location = {location}
use useState [location, setLocation] = useState(Cookies.get("currentlocation")) or  useState('epubcfi(....)')
