### ISSUE TITLE
How to set width of the ReactEpubViewer

### ISSUE THREAD

**Issue by abdulwahabone** [altmshfkgudtjr/react-epub-viewer#88]
Thanks for this amazing tool. I was having issues setting width of the ReactEpubViewer. I have tried using viewerStyle as per docs.

```
      <ReactEpubViewer
        viewerStyle={{ width: '300px' }}
        ref={viewerRef}
        onPageChange={onPageChange}
        url={url}
      />
```

**Comment by abdulwahabone** [comment]
Hi @altmshfkgudtjr 
Any update on this, any help will be really appreciated.

**Comment by altmshfkgudtjr** [comment]
Sorry for replying so late.

This is an issue that was not considered in the ReactEpubViewer component.

I'll add it to the TODO after running some more tests.

Currently, the workaround is as follows:

Change ReactEpubViewer component to EpubViewer component.
And enter the maximum horizontal length in the parent component that surrounds the viewer.

This is sample with CodeSandbox.
https://codesandbox.io/s/react-playground-forked-bk2iz7?file=/index.js

![image](https://user-images.githubusercontent.com/47492535/208000070-88ce1496-0730-4c73-8f38-669bade85dee.png)
