### ISSUE TITLE
adding word translations as inline annotation

### ISSUE THREAD

**Issue by chuan137** [altmshfkgudtjr/react-epub-viewer#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
just as the title says, I would like to have word translation annotated in the text. It will be a convenient feature when reading books not in mother tongue. Maybe I have missed it, but I have not found any epub reader supporting this except kindle. Maybe we can use kindle as an expiration, what the end result should look like.

**Describe alternatives you've considered**

**Additional context**

**Comment by altmshfkgudtjr** [comment]
When we have enough time, we will expand to import more custom features.
