### ISSUE TITLE
Automatically added some string at url

### ISSUE THREAD

**Issue by ariealdiansyah** [altmshfkgudtjr/react-epub-viewer#97]
**Describe the bug**
I try to open epub using url with signature but when i pass the url from props, the url automatically added string **/META-INF/container.xml** on the last string of url

How do I make my url link not automatically added to the string ?

**Comment by altmshfkgudtjr** [comment]
That path is the path inside the epub file. If you have a capture, I think it will give you a clearer perception of your situation. 😀
